--ZAD 1
SELECT * FROM ZESPOLY;

--ZAD 2
SELECT * FROM PRACOWNICY;

--ZAD 3
SELECT NAZWISKO, PLACA_POD*12 FROM PRACOWNICY;

--ZAD 4
SELECT ETAT, PLACA_POD + COALESCE(PLACA_DOD, 0) AS MIESIECZNE_ZAROBKI FROM PRACOWNICY;

--ZAD 5
SELECT * FROM ZESPOLY ORDER BY NAZWA;

--ZAD 6
SELECT UNIQUE ETAT FROM PRACOWNICY;

--ZAD 7
SELECT * FROM PRACOWNICY WHERE ETAT ='ASYSTENT';

--ZAD 8
SELECT * FROM PRACOWNICY WHERE ID_ZESP=30 OR ID_ZESP=40 ORDER BY PLACA_POD DESC;

--ZAD 9
SELECT NAZWISKO, ID_ZESP, PLACA_POD FROM PRACOWNICY WHERE PLACA_POD < 800 AND PLACA_POD > 300;

--ZAD 10
SELECT NAZWISKO, ETAT, ID_ZESP FROM PRACOWNICY WHERE NAZWISKO LIKE '%SKI';

--ZAD 11
SELECT  ID_PRAC, ID_SZEFA, NAZWISKO, PLACA_POD FROM PRACOWNICY WHERE ID_SZEFA IS NOT NULL AND PLACA_POD>1000;

--ZAD 12
SELECT NAZWISKO, ID_ZESP FROM PRACOWNICY WHERE ID_ZESP = 20 AND (NAZWISKO LIKE '%SKI' OR NAZWISKO LIKE 'M%');

--ZAD 13
SELECT NAZWISKO, ETAT, PLACA_POD/(20*8) AS STAWKA FROM PRACOWNICY WHERE ETAT NOT IN ('ADIUNKT', 'ASYSTENT', 'STAZYSTA') AND PLACA_POD NOT BETWEEN 400 AND 800 ORDER BY STAWKA ASC;

--ZAD 14
SELECT NAZWISKO, ETAT, PLACA_POD, PLACA_DOD FROM PRACOWNICY WHERE PLACA_POD + COALESCE(placa_dod, 0) > 1000 ORDER BY ETAT, NAZWISKO;

--ZAD 15
SELECT NAZWISKO || ' PRACUJE OD ' || ZATRUDNIONY || ' I ZARABIA ' || PLACA_POD AS PROFESOROWIE FROM PRACOWNICY WHERE ETAT = 'PROFESOR';