--ZADANIE 1
/*CREATE OR REPLACE PROCEDURE
PODWYZKA(P_ID_ZESP IN NUMBER, P_PROCENT IN NUMBER DEFAULT 15) IS
    BEGIN
        UPDATE PRACOWNICY
            SET PLACA_POD = PLACA_POD * (P_PROCENT/100 + 1)
            WHERE ID_ZESP = P_ID_ZESP;    
    END PODWYZKA;
/
--COMMIT;
SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY WHERE ID_ZESP = 10;
DECLARE
    P_LICZ NUMBER := 10;
BEGIN
    PODWYZKA(P_LICZ,P_LICZ);
END;
/
SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY WHERE ID_ZESP = 10;

--ZADANIE 2
CREATE OR REPLACE PROCEDURE
PODWYZKA(P_ID_ZESP IN NUMBER, P_PROCENT IN NUMBER DEFAULT 15) IS
    POM_ZESP ZESPOLY.NAZWA%TYPE;
    BEGIN
        SELECT NAZWA INTO POM_ZESP FROM ZESPOLY WHERE ID_ZESP = P_ID_ZESP;
        UPDATE PRACOWNICY
            SET PLACA_POD = PLACA_POD * (P_PROCENT/100 + 1)
            WHERE ID_ZESP = P_ID_ZESP;
    EXCEPTION
        WHEN no_data_found THEN
        RAISE_APPLICATION_ERROR(-20000, 'BRAK ZESPOLU O NUMERZE: '||P_ID_ZESP);
    END PODWYZKA;
/
SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY WHERE ID_ZESP = 12;
DECLARE
    P_LICZ NUMBER := 12;
BEGIN
    PODWYZKA(P_LICZ,P_LICZ);
END;
/
SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY WHERE ID_ZESP = 12;

--ZADANIE 5
CREATE OR REPLACE FUNCTION
PLACA_NETTO(P_PLACA IN NUMBER, P_PODATEK IN NUMBER DEFAULT 15) RETURN NUMBER IS
    V_WYNIK PRACOWNICY.PLACA_POD%TYPE;
    BEGIN
        V_WYNIK := P_PLACA - P_PLACA * (P_PODATEK/100);
        RETURN V_WYNIK;
    END PLACA_NETTO;
/
--EXECUTE PLACA_NETTO(1200, 10);
SELECT NAZWISKO, PLACA_POD BRUTTO, PLACA_NETTO(PLACA_POD,35) NETTO
FROM PRACOWNICY WHERE ETAT = 'PROFESOR';
*/

--WYZWALACZE
CREATE SEQUENCE ZESP_SEQ START WITH 60 INCREMENT BY 10;

CREATE OR REPLACE TRIGGER WYZWALACZ
BEFORE INSERT ON ZESPOLY
FOR EACH ROW
BEGIN
    IF(:NEW.ID_ZESP IS NULL) THEN
        :NEW.ID_ZESP := ZESP_SEQ.NEXTVAL;
    END IF;
END;
/
INSERT INTO ZESPOLY(NAZWA) VALUES('KRYPTOGRAFIA'); 
/
INSERT INTO ZESPOLY(NAZWA) SELECT substr('NOWE '||NAZWA,1,20) FROM ZESPOLY
WHERE ID_ZESP in (10,20);
/
SELECT * FROM ZESPOLY;


