SELECT NAZWISKO, SUBSTR(ETAT, 1,2)|| ID_PRAC AS KOD FROM PRACOWNICY;

SELECT NAZWISKO, TRANSLATE(NAZWISKO, 'KLM', 'XXX') AS WOJNA_LITEROM FROM PRACOWNICY;

SELECT NAZWISKO FROM PRACOWNICY WHERE INSTR(SUBSTR(NAZWISKO,1,LENGTH(NAZWISKO)/2), 'L', 1, 1)>0;

SELECT NAZWISKO, ROUND(PLACA_POD*1.15, 0) AS PODWYZKA FROM PRACOWNICY;

SELECT NAZWISKO, PLACA_POD, 0.2*PLACA_POD AS INWESTYCJA, 0.2*PLACA_POD*POWER(1.1, 10) AS KAPITAL, 0.2*PLACA_POD*POWER(1.1, 10) - 0.2*PLACA_POD AS ZYSK FROM PRACOWNICY;

SELECT nazwisko,ZATRUDNIONY, EXTRACT(YEAR FROM (DATE '2000-01-01' - zatrudniony) YEAR TO MONTH) AS staz_w_2000_r FROM pracownicy;

SELECT NAZWISKO, TO_CHAR(ZATRUDNIONY, 'MONTH, DD YYYY' ) FROM PRACOWNICY WHERE ID_ZESP=20;

SELECT DISTINCT TO_CHAR(CURRENT_DATE, 'DAY') AS DZIS FROM PRACOWNICY;

SELECT NAZWA, ADRES, 
    CASE ADRES
        WHEN 'PIOTROWO 3A' THEN 'NOWE MIASTO'
        WHEN 'STRZELECKA 14' THEN 'STARE MIASTO'
        WHEN 'MIELZYNSKIEGO 30' THEN 'STARE MIASTO'
        WHEN 'WLODKOWICA 16' THEN 'GRUNWALD'
        ELSE ' '
    END AS DZIELNICA FROM ZESPOLY;
    

SELECT NAZWISKO, PLACA_POD,
    CASE
        WHEN PLACA_POD>480 THEN 'POWYZEJ 480'
        WHEN PLACA_POD<480 THEN 'PONIZEJ 480'
        WHEN PLACA_POD=480 THEN 'DOKLADNIE 480'
        ELSE ' '
    END AS PROG FROM PRACOWNICY;
    
SELECT NAZWISKO, PLACA_POD,
    DECODE(SIGN(PLACA_POD-480),
        1, 'POWYZEJ 480',
        -1, 'PONIZEJ 480',
        0, 'DOKLADNIE 480',
        ' '
    )AS PROG FROM PRACOWNICY;
    

