SELECT MIN(PLACA_POD) AS MINIMUM, MAX(PLACA_POD) AS MAKSIMUM, MAX(PLACA_POD) - MIN(PLACA_POD) AS ROZNICA FROM PRACOWNICY;

SELECT ETAT, AVG(PLACA_POD) AS SREDNIA FROM PRACOWNICY GROUP BY ETAT ORDER BY AVG(PLACA_POD) DESC;

SELECT ETAT, COUNT(*) AS ILOSC FROM PRACOWNICY WHERE ETAT='PROFESOR' GROUP BY ETAT;

SELECT ID_ZESP, SUM(PLACA_POD)+SUM(PLACA_DOD) AS PLACA FROM PRACOWNICY GROUP BY ID_ZESP ORDER BY ID_ZESP ASC;

SELECT MAX(SUM(PLACA_POD)+SUM(PLACA_DOD)) AS MAX_PLACA FROM PRACOWNICY GROUP BY ID_ZESP;

SELECT ID_SZEFA, MIN(PLACA_POD) FROM PRACOWNICY GROUP BY ID_SZEFA ORDER BY MIN(PLACA_POD) DESC;

SELECT ID_ZESP, COUNT(*) FROM PRACOWNICY GROUP BY ID_ZESP ORDER BY COUNT(*) DESC;

SELECT ID_ZESP, COUNT(*) AS LICZBA FROM PRACOWNICY GROUP BY ID_ZESP HAVING COUNT(*)>2 ORDER BY COUNT(*) DESC;

SELECT ID_PRAC FROM PRACOWNICY GROUP BY ID_PRAC HAVING COUNT(*)>1;

SELECT ETAT, AVG(PLACA_POD) AS SREDNIA, COUNT(*) AS LICZBA FROM PRACOWNICY WHERE EXTRACT(YEAR FROM ZATRUDNIONY)<1990 GROUP BY ETAT;

SELECT ID_ZESP, ETAT, ROUND(AVG(PLACA_POD)) AS SREDNIA, MAX(PLACA_POD) AS MAKS FROM PRACOWNICY GROUP BY ID_ZESP, ETAT HAVING ETAT IN ('PROFESOR','ASYSTENT') ORDER BY ID_ZESP, ETAT ASC ;

SELECT EXTRACT(YEAR FROM ZATRUDNIONY) AS ROK, COUNT(*) AS ILOSC FROM PRACOWNICY GROUP BY EXTRACT(YEAR FROM ZATRUDNIONY) ORDER BY EXTRACT(YEAR FROM ZATRUDNIONY) ASC;

SELECT LENGTH(NAZWISKO) AS ILE_LITER, COUNT(*) AS ILE_LUDZI FROM PRACOWNICY GROUP BY LENGTH(NAZWISKO) ORDER BY LENGTH(NAZWISKO) ASC;

SELECT SUM(CASE WHEN LOWER(NAZWISKO) LIKE '%a%' THEN 1 END)AS I_A, SUM(CASE WHEN LOWER(NAZWISKO) LIKE '%e%' THEN 1 END) AS I_E FROM PRACOWNICY;

SELECT ID_ZESP, SUM(PLACA_POD) AS SUMA, LISTAGG(NAZWISKO||':'||PLACA_POD,';') WITHIN GROUP(ORDER BY PLACA_POD ASC) AS PRACOWNICY FROM PRACOWNICY GROUP BY ID_ZESP ORDER BY ID_ZESP;