SELECT NAZWISKO, ETAT, PRACOWNICY.ID_ZESP, NAZWA FROM PRACOWNICY, ZESPOLY WHERE PRACOWNICY.ID_ZESP=ZESPOLY.ID_ZESP ORDER BY NAZWISKO;

SELECT NAZWISKO, ETAT, PRACOWNICY.ID_ZESP, ADRES FROM PRACOWNICY, ZESPOLY WHERE ADRES='PIOTROWO 3A' AND PRACOWNICY.ID_ZESP=ZESPOLY.ID_ZESP ORDER BY NAZWISKO;

SELECT NAZWISKO, ADRES, NAZWA FROM PRACOWNICY, ZESPOLY WHERE PLACA_POD > 400 AND PRACOWNICY.ID_ZESP=ZESPOLY.ID_ZESP ORDER BY NAZWISKO;

SELECT NAZWISKO, PLACA_POD, PRACOWNICY.ETAT, ETATY.NAZWA AS KAT_PLAC, PLACA_MIN, PLACA_MAX FROM PRACOWNICY JOIN ETATY ON PLACA_POD BETWEEN PLACA_MIN AND PLACA_MAX ORDER BY NAZWISKO, KAT_PLAC;

SELECT NAZWISKO, PLACA_POD, PRACOWNICY.ETAT, ETATY.NAZWA AS KAT_PLAC, PLACA_MIN, PLACA_MAX FROM PRACOWNICY JOIN ETATY ON ETATY.NAZWA='SEKRETARKA' AND PLACA_POD BETWEEN PLACA_MIN AND PLACA_MAX ORDER BY PLACA_POD DESC;

SELECT NAZWISKO, PLACA_POD, PRACOWNICY.ETAT, ETATY.NAZWA AS KAT_PLAC, ZESPOLY.NAZWA FROM PRACOWNICY, ETATY, ZESPOLY WHERE PRACOWNICY.ETAT NOT LIKE 'ASYSTENT'AND PLACA_POD BETWEEN PLACA_MIN AND PLACA_MAX AND PRACOWNICY.ID_ZESP=ZESPOLY.ID_ZESP ORDER BY PLACA_POD DESC;

SELECT NAZWISKO, ETAT, PLACA_POD*12 + COALESCE(PLACA_DOD, 0) AS PLACA_ROCZ, ZESPOLY.NAZWA, ETATY.NAZWA AS KAT_PLAC FROM PRACOWNICY, ETATY , ZESPOLY WHERE PRACOWNICY.ID_ZESP=ZESPOLY.ID_ZESP AND (ETAT='ASYSTENT' OR ETAT='ADIUNKT') AND PLACA_POD*12 + COALESCE(PLACA_DOD, 0) > 5500 AND PLACA_POD BETWEEN PLACA_MIN AND PLACA_MAX ORDER BY NAZWISKO;

SELECT P.NAZWISKO, P.ID_PRAC, S.NAZWISKO, P.ID_SZEFA FROM PRACOWNICY P, PRACOWNICY S WHERE P.ID_SZEFA = S.ID_PRAC ORDER BY NAZWISKO;

SELECT P.NAZWISKO, P.ID_PRAC, S.NAZWISKO, P.ID_SZEFA FROM PRACOWNICY P LEFT OUTER JOIN PRACOWNICY S ON P.ID_SZEFA = S.ID_PRAC ORDER BY P.NAZWISKO;

SELECT NAZWA, COUNT(NAZWISKO) AS LICZBA, AVG(PLACA_POD) AS SREDNIA FROM PRACOWNICY P RIGHT OUTER JOIN ZESPOLY Z ON P.ID_ZESP=Z.ID_ZESP GROUP BY NAZWA ORDER BY NAZWA;  

SELECT S.NAZWISKO, COUNT(P.NAZWISKO) AS PODWLADNI FROM PRACOWNICY S, PRACOWNICY P WHERE  P.ID_SZEFA=S.ID_PRAC GROUP BY P.ID_SZEFA, S.NAZWISKO ORDER BY COUNT(P.ID_SZEFA);




