SELECT NAZWISKO, ETAT, ID_ZESP FROM PRACOWNICY 
    WHERE ID_ZESP=(SELECT DISTINCT ID_ZESP FROM PRACOWNICY WHERE NAZWISKO = 'BRZEZINSKI');
    
SELECT NAZWISKO, ETAT, ZATRUDNIONY FROM PRACOWNICY 
    WHERE ZATRUDNIONY=(SELECT MIN(ZATRUDNIONY) FROM PRACOWNICY WHERE ETAT='PROFESOR');
    
SELECT NAZWISKO, ZATRUDNIONY, ID_ZESP FROM PRACOWNICY 
    WHERE (ZATRUDNIONY, ID_ZESP) IN (SELECT MAX(ZATRUDNIONY), ID_ZESP FROM PRACOWNICY GROUP BY ID_ZESP) ORDER BY ZATRUDNIONY ASC;

SELECT ID_ZESP, NAZWA, ADRES FROM ZESPOLY Z 
    WHERE NOT EXISTS (SELECT ID_ZESP FROM PRACOWNICY WHERE ID_ZESP = Z.ID_ZESP);

SELECT NAZWISKO, PLACA_POD, ETAT FROM PRACOWNICY P 
    WHERE P.PLACA_POD > (SELECT AVG(PLACA_POD) FROM PRACOWNICY WHERE ETAT = P.ETAT);
    
SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY P 
    WHERE P.PLACA_POD >= 0.75*(SELECT PLACA_POD FROM PRACOWNICY WHERE P.ID_SZEFA = ID_PRAC);

SELECT NAZWISKO FROM PRACOWNICY S 
    WHERE ETAT = 'PROFESOR' AND NOT EXISTS(SELECT 1 FROM PRACOWNICY WHERE S.ID_PRAC = ID_SZEFA AND ETAT = 'STAZYSTA');
    
SELECT ID_ZESP, SUM(PLACA_POD) FROM PRACOWNICY  GROUP BY ID_ZESP HAVING SUM(PLACA_POD)=(SELECT MAX(SUM(PLACA_POD)) FROM PRACOWNICY GROUP BY ID_ZESP);

SELECT ROK, COUNT(ID_PRAC) FROM (SELECT EXTRACT(YEAR FROM ZATRUDNIONY) AS ROK, ID_PRAC FROM PRACOWNICY) GROUP BY ROK ORDER BY COUNT(ID_PRAC) DESC; 

SELECT ROK, COUNT(ID_PRAC) FROM (SELECT EXTRACT(YEAR FROM ZATRUDNIONY) AS ROK, ID_PRAC FROM PRACOWNICY) GROUP BY ROK ORDER BY COUNT(ID_PRAC) DESC ; 
