INSERT INTO PRACOWNICY 
VALUES (250, 'KOWALSKI', 'ASYSTENT', NULL, DATE '2015-01-13', 1500, NULL, 10);

INSERT INTO PRACOWNICY 
VALUES (260, 'ADAMSKI', 'ASYSTENT', NULL, DATE '2014-09-10', 1500, NULL, 10);

INSERT INTO PRACOWNICY 
VALUES (270, 'NOWAK', 'ADIUNKT', NULL, DATE '1990-05-01', 2050, 540, 20);

COMMIT;

SELECT * FROM PRACOWNICY WHERE NAZWISKO IN ('KOWALSKI', 'ADAMSKI', 'NOWAK');

UPDATE PRACOWNICY 
SET PLACA_POD = PLACA_POD*1.1,
    PLACA_DOD = COALESCE(PLACA_DOD*1.2, 100)

WHERE ID_PRAC IN (250,260,270);

SELECT * FROM PRACOWNICY WHERE NAZWISKO IN ('KOWALSKI', 'ADAMSKI', 'NOWAK');

COMMIT;

INSERT INTO ZESPOLY
VALUES (60, 'BAZY DANYCH', 'PIOTROWO 2');

SELECT * FROM ZESPOLY WHERE NAZWA='BAZY DANYCH';

COMMIT;

UPDATE PRACOWNICY 
SET ID_ZESP = (SELECT Z.ID_ZESP FROM ZESPOLY Z WHERE Z.NAZWA='BAZY DANYCH')

WHERE ID_PRAC IN (250,260,270);

SELECT * FROM PRACOWNICY WHERE ID_ZESP=60;

COMMIT;

UPDATE PRACOWNICY
SET ID_SZEFA = (SELECT ID_PRAC FROM PRACOWNICY WHERE NAZWISKO = 'MORZY')

WHERE ID_PRAC IN (250,260,270);

SELECT * FROM PRACOWNICY WHERE ID_SZEFA = 140;

COMMIT;

DELETE FROM PRACOWNICY WHERE ID_ZESP=60;
DELETE FROM ZESPOLY WHERE NAZWA='BAZY DANYCH';

COMMIT;

SELECT P.NAZWISKO, P.PLACA_POD, PODWYZKA FROM PRACOWNICY P JOIN (SELECT D.ID_ZESP, 0.1*AVG(D.PLACA_POD) AS PODWYZKA FROM PRACOWNICY D GROUP BY D.ID_ZESP) S  ON P.ID_ZESP=S.ID_ZESP; 

UPDATE PRACOWNICY X
SET X.PLACA_POD = (SELECT P.PLACA_POD+PODWYZKA 
                    FROM PRACOWNICY P 
                    JOIN (SELECT D.ID_ZESP, 0.1*AVG(D.PLACA_POD) AS PODWYZKA 
                            FROM PRACOWNICY D GROUP BY D.ID_ZESP) S  ON P.ID_ZESP=S.ID_ZESP WHERE P.ID_PRAC = X.ID_PRAC);
                        
                        
SELECT * FROM PRACOWNICY;

COMMIT;



                            