--SEQUENCES EXCERCISES

CREATE SEQUENCE PRAC_SEQ START WITH 300 INCREMENT BY 10;

INSERT INTO PRACOWNICY 
VALUES (PRAC_SEQ.NEXTVAL, 'TRABCZYNSKI', 'STAZYSTA', NULL, NULL, 1000, 300, NULL);

SELECT * FROM PRACOWNICY;

DELETE FROM PRACOWNICY WHERE ID_PRAC=300;

--DDL EXCERCISES

CREATE TABLE PROJEKTY
    (ID_PROJKETU NUMBER(4) GENERATED ALWAYS AS IDENTITY,
    OPIS_PROJEKTU VARCHAR2(20 BYTE),
    DATA_ROZPOCZECIA DATE DEFAULT CURRENT_DATE,
    DATA_ZAKONCZENIA DATE,
    FUNDUSZ NUMBER(7,2));
    
INSERT INTO PROJEKTY(OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ) 
    VALUES('INDEKSY BITMAPOWE', DATE '1999-04-01', DATE '2001-08-31', 25000); 
    
INSERT INTO PROJEKTY(OPIS_PROJEKTU, FUNDUSZ) 
    VALUES('SIECI KREGOSLUPOWE', 19000); 

SELECT * FROM PROJEKTY;

INSERT INTO PROJEKTY(OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ) 
    VALUES('INDEKSY DRZEWIASTE', DATE '2013-12-24', DATE '2014-01-01', 1200);
    
--UPDATE PROJEKTY
    --SET ID_PROJEKTU=10
    --WHERE OPIS_PROJEKTU='INDEKSY DRZEWIASTE';

CREATE TABLE PROJEKTY_KOPIA AS SELECT * FROM PROJEKTY;

SELECT * FROM PROJEKTY_KOPIA;

INSERT INTO PROJEKTY_KOPIA
    VALUES(10, 'SIECI LOKALNE',CURRENT_DATE, CURRENT_DATE+INTERVAL '1' YEAR, 24500);
    
DELETE FROM PROJEKTY WHERE OPIS_PROJEKTU='INDEKSY DRZEWIASTE';

SELECT TABLE_NAME FROM USER_TABLES;

    

