ALTER TABLE PROJEKTY
    ADD CONSTRAINT PK_PROJEKTY PRIMARY KEY(ID_PROJEKTU);
ALTER TABLE PROJEKTY
    ADD CONSTRAINT UK_PROJEKTY UNIQUE(OPIS_PROJEKTU);
ALTER TABLE PROJEKTY
    MODIFY OPIS_PROJEKTU NOT NULL;
ALTER TABLE PROJEKTY
    ADD CHECK(DATA_ZAKONCZENIA>DATA_ROZPOCZECIA);
ALTER TABLE PROJEKTY
    ADD CHECK(FUNDUSZ>0);

INSERT INTO PROJEKTY(OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ) 
    VALUES('INDEKSY BITMAPOWE', DATE '1999-04-01', DATE '2001-08-31', 25000); 
    
SELECT * FROM PROJEKTY;

--ALTER TABLE PROJEKTY RENAME COLUMN ID_PROJKETU TO ID_PROJEKTU;

CREATE TABLE PRZYDZIALY
    (ID_PROJEKTU NUMBER(4) CONSTRAINT FK_PRZYDZIALY_01 REFERENCES PROJEKTY(ID_PROJEKTU) ,
    NR_PRACOWNIKA NUMBER(6)CONSTRAINT FK_PRZYDZIALY_02 REFERENCES PRACOWNICY(ID_PRAC),
    OD DATE DEFAULT CURRENT_DATE,
    DO DATE, CONSTRAINT CHK_PRZYDZIALY_DATY CHECK(DO>OD),
    STAWKA NUMBER(7,2) CONSTRAINT CHK_PRZYDZIALY_STAWKA CHECK(STAWKA>0),
    ROLA VARCHAR2(20 BYTE) CONSTRAINT  CHK_PRZYDZIALY_ROLA CHECK(ROLA IN ('KIERUJACY','ANALITYK','PROGRAMISTA')),
    CONSTRAINT  PK_PRZYDZIALY PRIMARY KEY(ID_PROJEKTU, NR_PRACOWNIKA)
    );
    
INSERT INTO PRZYDZIALY(ID_PROJEKTU, NR_PRACOWNIKA,OD, DO, STAWKA, ROLA) 
    VALUES( (SELECT ID_PROJEKTU FROM PROJEKTY WHERE OPIS_PROJEKTU='INDEKSY BITMAPOWE'),
    170, DATE '1999-04-10', DATE '1999-05-10', 1000, 'KIERUJACY');
    
INSERT INTO PRZYDZIALY(ID_PROJEKTU, NR_PRACOWNIKA,OD, DO, STAWKA, ROLA) 
    VALUES( (SELECT ID_PROJEKTU FROM PROJEKTY WHERE OPIS_PROJEKTU='INDEKSY BITMAPOWE'),
    140, DATE '2000-12-01', NULL, 1500, 'ANALITYK');
    
INSERT INTO PRZYDZIALY(ID_PROJEKTU, NR_PRACOWNIKA,OD, DO, STAWKA, ROLA) 
    VALUES( (SELECT ID_PROJEKTU FROM PROJEKTY WHERE OPIS_PROJEKTU='SIECI KREGOSLUPOWE'),
    140, DATE '2015-09-14', NULL, 2500, 'KIERUJACY');
    
SELECT * FROM PRZYDZIALY;

ALTER TABLE PRZYDZIALY
ADD GODZINY NUMBER(4) CHECK(GODZINY<9999) NOT NULL;

ALTER TABLE PRZYDZIALY
    ADD GODINY NUMBER(4);
UPDATE PRZYDZIALY
    SET GODINY=200;
ALTER TABLE PRZYDZIALY
    MODIFY GODINY CHECK(GODINY<9999);
    
ALTER TABLE PROJEKTY
DISABLE CONSTRAINT UK_PROJEKTY;

SELECT CONSTRAINT_NAME, STATUS FROM USER_CONSTRAINTS;

